import { GameConfig } from "../../gameConfig";
import { v2 } from "../../utils/v2";
import type { MapDef } from "../mapDefs";
import { MapId } from "../types/misc";

// @NOTE: Entries defined as single-element arrays, like fixedSpawns: [{ }],
// are done this way so that util.mergeDeep(...) will function as expected
// when used by derivative maps.
//
// Arrays are not mergeable, so the derived map will always redefine all
// elements if that property is set.

export const Main: MapDef = {
    mapId: MapId.Main,
    desc: { name: "Normal", icon: "", buttonCss: "" },
    assets: {
        audio: [
            { name: "club_music_01", channel: "ambient" },
            { name: "club_music_02", channel: "ambient" },
            { name: "ambient_steam_01", channel: "ambient" },
            { name: "log_11", channel: "sfx" },
            { name: "log_12", channel: "sfx" },
            { name: "snowball_01", channel: "sfx" },
        ],
        // snow because impulses use snowball textures
        atlases: ["gradient", "loadout", "shared", "main", "snow"],
    },
    biome: {
        colors: {
            background: 0x20536e,
            water: 0x3282ab,
            waterRipple: 0xb3f0ff,
            beach: 0xcdb35b,
            riverbank: 0x905e24,
            grass: 0x80af49,
            underground: 0x1b0d03,
            playerSubmerge: 0x2b8ca4,
            playerGhillie: 0x83af50,
        },
        valueAdjust: 1,
        sound: { riverShore: "sand" },
        particles: { camera: "" },
        tracerColors: {},
        airdrop: {
            planeImg: "map-plane-01.img",
            planeSound: "plane_01",
            airdropImg: "map-chute-01.img",
        },
    },
    gameMode: {
        maxPlayers: 80,
        killLeaderEnabled: true,
    },
    gameConfig: {
        planes: {
            timings: [
                {
                    circleIdx: 1,
                    wait: 0,
                    options: { type: GameConfig.Plane.Airdrop },
                },
                {
                    circleIdx: 2,
                    wait: 0,
                    options: { type: GameConfig.Plane.Airdrop },
                },
                {
                    circleIdx: 3,
                    wait: 0,
                    options: { type: GameConfig.Plane.Airdrop },
                },
                {
                    circleIdx: 4,
                    wait: 0,
                    options: { type: GameConfig.Plane.Airdrop },
                },
            ],
            crates: [
                { name: "airdrop_crate_01", weight: 10 },
                { name: "airdrop_crate_02", weight: 1 },
            ],
        },
        bagSizes: {},
        bleedDamage: 2,
        bleedDamageMult: 1,
    },
    /* STRIP_FROM_PROD_CLIENT:START */
    // NOTE: this loot table is not the original one so its not accurate
    // ? are guesses based on statistics
    // ! are uncertain data based on leak
    lootTable: {
        tier_club_bonus: [
            { name: "model94", count: 1, weight: 1 },
            { name: "an94", count: 1, weight: 1 },
        ],
        tier_world: [
            { name: "tier_scopes", count: 1, weight: 1 },
            { name: "tier_armor", count: 1, weight: 1.7 },
            { name: "tier_packs", count: 1, weight: 0.5 },
            { name: "tier_medical", count: 1, weight: 1.5 },
            { name: "tier_ammo", count: 1, weight: 2.5 },
            { name: "tier_guns", count: 1, weight: 2 },
        ],
        tier_surviv: [
            { name: "tier_scopes", count: 1, weight: 1 },
            { name: "tier_armor", count: 1, weight: 1.2 },
            { name: "tier_medical", count: 1, weight: 4 },
            { name: "tier_packs", count: 1, weight: 1 },
        ],
        tier_bugler_crate: [
            { name: "model94", count: 1, weight: 1 },
            { name: "an94", count: 1, weight: 1 },
        ],
        tier_container: [
            { name: "tier_scopes", count: 1, weight: 0.2 },
            { name: "tier_armor", count: 1, weight: 1 },
            { name: "tier_packs", count: 1, weight: 0.3 },
            { name: "tier_medical", count: 1, weight: 0.8 },
            { name: "tier_ammo", count: 1, weight: 0.5 },
            { name: "tier_guns", count: 1, weight: 0.6 },
        ],
        tier_leaf_pile: [
            { name: "tier_scopes", count: 1, weight: 1 },
            { name: "tier_armor", count: 1, weight: 1.5 },
            { name: "tier_packs", count: 1, weight: 1 },
            { name: "tier_medical", count: 1, weight: 1 },
            { name: "tier_ammo", count: 1, weight: 1 },
        ],
        tier_soviet: [
            { name: "tier_scopes", count: 1, weight: 1 },
            { name: "tier_armor", count: 1, weight: 1.5 },
            { name: "tier_packs", count: 1, weight: 1 },
            { name: "tier_medical", count: 1, weight: 2 },
            { name: "tier_ammo", count: 1, weight: 3 },
            { name: "tier_guns", count: 1, weight: 6 },
        ],
        tier_toilet: [
            { name: "tier_scopes", count: 1, weight: 0.5 },
            { name: "tier_guns", count: 1, weight: 0.2 },
            { name: "tier_medical", count: 1, weight: 1.0 },
        ],
        tier_scopes: [
            { name: "2xscope", count: 1, weight: 0.6 },
            { name: "4xscope", count: 1, weight: 1 },
            { name: "8xscope", count: 1, weight: 0 },
            { name: "15xscope", count: 1, weight: 0 },
        ],
        tier_armor: [
            { name: "helmet01", count: 1, weight: 8.5 },
            { name: "helmet02", count: 1, weight: 7 },
            { name: "helmet03", count: 1, weight: 3 },
            { name: "chest01", count: 1, weight: 8.5 },
            { name: "chest02", count: 1, weight: 7 },
            { name: "chest03", count: 1, weight: 3 },
        ],
        tier_packs: [
            { name: "backpack01", count: 1, weight: 7 },
            { name: "backpack02", count: 1, weight: 4 },
            { name: "backpack03", count: 1, weight: 1 },
        ],
        tier_medical: [
            { name: "bandage", count: 5, weight: 6 },
            { name: "healthkit", count: 1, weight: 4 },
            { name: "soda", count: 1, weight: 13 },
            { name: "painkiller", count: 1, weight: 6 },
        ],
        tier_throwables: [
            { name: "frag", count: 1, weight: 1 },
            { name: "smoke", count: 1, weight: 1 },
            { name: "snowball", count: 1, weight: 0 },
            { name: "mirv", count: 1, weight: 0.05 },
        ],
        tier_ammo: [
            { name: "9mm", count: 60, weight: 8 },
            { name: "762mm", count: 60, weight: 8 },
            { name: "556mm", count: 60, weight: 8 },
            { name: "12gauge", count: 10, weight: 10 },
        ],
        tier_ammo_crate: [
            { name: "9mm", count: 60, weight: 5 },
            { name: "762mm", count: 60, weight: 5 },
            { name: "556mm", count: 60, weight: 5 },
            { name: "12gauge", count: 10, weight: 7 },
            { name: "50AE", count: 21, weight: 1 },
            { name: "308sub", count: 5, weight: 1 },
            { name: "flare", count: 1, weight: 1 },
        ],
        tier_vending_soda: [
            { name: "soda", count: 1, weight: 6 },
            // { name: "tier_ammo", count: 1, weight: 1 },
        ],
        tier_sv98: [
            { name: "sv98", count: 1, weight: 10 },
            { name: "", count: 1, weight: 0 },
        ],
        tier_mosin: [
            { name: "mosin", count: 1, weight: 10 },
            { name: "", count: 1, weight: 0 },
        ],
        tier_scout: [
            { name: "scout_elite", count: 1, weight: 10 },
            { name: "", count: 1, weight: 0 },
        ],
        tier_scopes_sniper: [
            { name: "4xscope", count: 1, weight: 0.2 },
            { name: "8xscope", count: 1, weight: 0 },
            { name: "15xscope", count: 1, weight: 0 },
        ],
        tier_mansion_floor: [{ name: "outfitCasanova", count: 1, weight: 1 }],
        tier_vault_floor: [{ name: "outfitJester", count: 1, weight: 1 }],
        tier_police_floor: [{ name: "outfitPrisoner", count: 1, weight: 1 }],
        tier_chrys_01: [{ name: "outfitImperial", count: 1, weight: 1 }],
        tier_chrys_02: [{ name: "katana", count: 1, weight: 1 }],
        tier_chrys_03: [
            //{ name: "2xscope", count: 1, weight: 1 },
            //{ name: "4xscope", count: 1, weight: 0.3 },
            //{ name: "8xscope", count: 1, weight: 0 },
            { name: "helmet04_medic", count: 1, weight: 1 },
        ],
        tier_chrys_case: [{ name: "", count: 1, weight: 1 }],
        tier_chrys_chest: [
            { name: "", count: 1, weight: 1 },
            { name: "katana", count: 1, weight: 1 },
            { name: "katana_rusted", count: 1, weight: 1 },
            { name: "katana_orchid", count: 1, weight: 1 },
        ],
        tier_eye_02: [{ name: "stonehammer", count: 1, weight: 1 }],
        tier_eye_block: [
            { name: "spas12", count: 1, weight: 1 },
            // { name: "ots38_dual", count: 1, weight: 1 },
            // { name: "flare_gun", count: 1, weight: 1 },
            // { name: "colt45", count: 1, weight: 1 },
            // { name: "45acp", count: 1, weight: 1 },
            // { name: "painkiller", count: 1, weight: 1 },
            // { name: "m4a1", count: 1, weight: 0.4 },
            //  { name: "m249", count: 1, weight: 0.05 },
            // { name: "awc", count: 1, weight: 0.05 },
            //{ name: "pkp", count: 1, weight: 0.05 },
        ],
        tier_sledgehammer: [{ name: "sledgehammer", count: 1, weight: 1 }],
        tier_chest_04: [
            { name: "p30l", count: 1, weight: 20 },
            { name: "p30l_dual", count: 1, weight: 1 },
        ],
        tier_woodaxe: [{ name: "woodaxe", count: 1, weight: 1 }],
        tier_club_melee: [{ name: "machete_taiga", count: 1, weight: 1 }],
        tier_guns: [
            { name: "famas", count: 1, weight: 2 },
            { name: "hk416", count: 1, weight: 8 },
            { name: "mk12", count: 1, weight: 0.9 },
            { name: "pkp", count: 1, weight: 0.0015 },
            { name: "m249", count: 1, weight: 0.006 },
            { name: "ak47", count: 1, weight: 8 },
            { name: "scar", count: 1, weight: 2 },
            { name: "dp28", count: 1, weight: 1.5 },
            // { name: "mosin", count: 1, weight: 0.2 *0.3 },
            { name: "m39", count: 1, weight: 0.8 },
            { name: "vss", count: 1, weight: 0.1 },
            { name: "mp5", count: 1, weight: 6 },
            { name: "mac10", count: 1, weight: 6 },
            { name: "ump9", count: 1, weight: 3 },
            { name: "m870", count: 1, weight: 12 },
            { name: "m1100", count: 1, weight: 0 },
            { name: "mp220", count: 1, weight: 4 },
            { name: "saiga", count: 1, weight: 0.1 },
            { name: "ot38", count: 1, weight: 3 },
            { name: "m9", count: 1, weight: 5 },
            { name: "m93r", count: 1, weight: 4 },
            { name: "glock", count: 1, weight: 4 },
            { name: "deagle", count: 1, weight: 0.5 },
            { name: "vector", count: 1, weight: 1 },
            // { name: "sv98", count: 1, weight: 0.03 * 0.9 },
            { name: "spas12", count: 1, weight: 3 },
            { name: "qbb97", count: 1, weight: 0.5 },
            { name: "flare_gun", count: 1, weight: 0.6 },
            { name: "flare_gun_dual", count: 1, weight: 0.00017 },
            { name: "groza", count: 1, weight: 2 },
            // { name: "scout_elite", count: 1, weight: 0.1 *0.3 },
            // { name: "blr", count: 1, weight: 0.5 *0.4 },
            { name: "scorpion", count: 1, weight: 0.5 },
            { name: "m4a1", count: 1, weight: 0.5 },
        ],
        tier_police: [
            { name: "scar", count: 1, weight: 1 },
            { name: "helmet03", count: 1, weight: 1 },
            { name: "chest03", count: 1, weight: 1 },
            { name: "backpack03", count: 1, weight: 1 },
        ],
        tier_ring_case: [
            { name: "grozas", count: 1, weight: 5 },
            { name: "ots38_dual", count: 1, weight: 0.1 },
            { name: "m9", count: 1, weight: 0 },
            { name: "pkp", count: 1, weight: 0.15 },
            // { name: "blr", count: 1, weight: 0.3 * 0.5 },
        ],
        tier_chest: [
            { name: "hk416", count: 1, weight: 2 },
            { name: "ak47", count: 1, weight: 13 },
            { name: "groza", count: 1, weight: 3 },
            { name: "famas", count: 1, weight: 1 },
            { name: "mk12", count: 1, weight: 4 },
            { name: "mp220", count: 1, weight: 10 },
            { name: "spas12", count: 1, weight: 9 },
            { name: "dp28", count: 1, weight: 1 },
            // { name: "mosin", count: 1, weight: 2 *0.4 },
            { name: "m39", count: 1, weight: 0.1 },
            { name: "scar", count: 1, weight: 2 },
            { name: "saiga", count: 1, weight: 2 },
            { name: "deagle", count: 1, weight: 0.7 },
            // { name: "sv98", count: 1, weight: 0.2 * 0.4},
            { name: "vector", count: 1, weight: 1 },
            { name: "m249", count: 1, weight: 1 },
            { name: "pkp", count: 1, weight: 0.3 },
            { name: "helmet01", count: 1, weight: 0 },
            { name: "helmet02", count: 1, weight: 0 },
            { name: "helmet03", count: 1, weight: 0 },
            { name: "4xscope", count: 1, weight: 0 },
            { name: "8xscope", count: 1, weight: 0 },
            { name: "blr", count: 1, weight: 1.5 },
            { name: "scorpion", count: 1, weight: 0.5 },
            { name: "m4a1", count: 1, weight: 0.5 },
        ],
        tier_conch: [
            { name: "outfitAqua", count: 1, weight: 1 },
            { name: "outfitCoral", count: 1, weight: 1 },
        ],
        tier_noir_outfit: [{ name: "outfitNoir", count: 1, weight: 1 }],
        tier_khaki_outfit: [{ name: "outfitKhaki", count: 1, weight: 1 }],
        tier_pirate_melee: [{ name: "hook", count: 1, weight: 1 }],
        tier_hatchet: [
            { name: "blr", count: 1, weight: 1 },
            // { name: "vector", count: 1, weight: 5 },
            // { name: "hk416", count: 1, weight: 2 },
            // { name: "mp220", count: 1, weight: 1 },
            // { name: "m249", count: 1, weight: 0.1 },
            // { name: "pkp", count: 1, weight: 0.05 },
            // { name: "m9", count: 1, weight: 0.01 },
        ],
        tier_lmgs: [
            { name: "bar", count: 1, weight: 5 },
            { name: "dp28", count: 1, weight: 5 },
            { name: "qbb97", count: 1, weight: 0.5 },
            { name: "m249", count: 1, weight: 0.01 },
            { name: "pkp", count: 1, weight: 0.01 },
        ],
        tier_shotguns: [
            { name: "m1100", count: 1, weight: 5 },
            { name: "m870", count: 1, weight: 5 },
            { name: "mp220", count: 1, weight: 1 },
            { name: "spas12", count: 1, weight: 1 },
            { name: "saiga", count: 1, weight: 0.1 },
            { name: "usas", count: 1, weight: 0 },
        ],
        tier_hatchet_melee: [
            { name: "fireaxe", count: 1, weight: 5 },
            { name: "katana", count: 1, weight: 1 },
            { name: "katana_rusted", count: 1, weight: 1 },
            { name: "katana_orchid", count: 1, weight: 0.1 },
            { name: "stonehammer", count: 1, weight: 0.1 },
        ],
        tier_pavilion: [
            { name: "dp28", count: 1, weight: 5 },
            { name: "bar", count: 1, weight: 5 },
            { name: "naginata", count: 1, weight: 1 },
            { name: "m9", count: 1, weight: 1 },
            { name: "pkp", count: 1, weight: 1 },
        ],
        tier_forest_helmet: [{ name: "helmet03_forest", count: 1, weight: 1 }],
        tier_imperial_outfit: [{ name: "outfitImperial", count: 1, weight: 1 }],
        tier_pineapple_outfit: [{ name: "outfitPineapple", count: 1, weight: 1 }],
        tier_tarkhany_outfit: [{ name: "outfitTarkhany", count: 1, weight: 1 }],
        tier_spetsnaz_outfit: [{ name: "outfitSpetsnaz", count: 1, weight: 1 }],
        tier_lumber_outfit: [{ name: "outfitLumber", count: 1, weight: 1 }],
        tier_verde_outfit: [{ name: "outfitVerde", count: 1, weight: 1 }],

        tier_airdrop_uncommon: [
            { name: "mk12", count: 1, weight: 0 },
            { name: "scar", count: 1, weight: 0 },
            { name: "vector", count: 1, weight: 0.75 },
            { name: "blr", count: 1, weight: 2.5 },
            { name: "mosin", count: 1, weight: 2 },
            { name: "saiga", count: 1, weight: 0 },
            { name: "deagle", count: 1, weight: 0 },
            { name: "sv98", count: 1, weight: 0.1 },
            { name: "qbb97", count: 1, weight: 1.5 },
            { name: "flare_gun", count: 1, weight: 0 },
            { name: "scout_elite", count: 1, weight: 1.5 },
        ],
        tier_airdrop_rare: [
            { name: "garand", count: 1, weight: 6 },
            { name: "mosin", count: 1, weight: 6 },
            { name: "pkp", count: 1, weight: 3 },
            { name: "m249", count: 1, weight: 0.1 },
            { name: "m4a1", count: 1, weight: 4 },
            { name: "scorpion", count: 1, weight: 5 },
            // { name: "ots38_dual", count: 1, weight: 4.5 },
        ],
        tier_airdrop_ammo: [
            { name: "45acp", count: 30, weight: 0 },
            { name: "762mm", count: 30, weight: 3 },
            { name: "556mm", count: 30, weight: 3 },
            { name: "12gauge", count: 5, weight: 3 },
        ],
        tier_airdrop_outfits: [
            { name: "", count: 1, weight: 20 },
            { name: "outfitMeteor", count: 1, weight: 0 },
            { name: "outfitHeaven", count: 1, weight: 0 },
            {
                name: "outfitGhillie",
                count: 0,
                weight: 0,
            },
        ],
        tier_airdrop_throwables: [
            { name: "frag", count: 2, weight: 1 },
            { name: "snowball", count: 2, weight: 0 },
            { name: "mirv", count: 2, weight: 0.5 },
        ],
        tier_airdrop_melee: [
            { name: "", count: 1, weight: 19 },
            { name: "katana", count: 1, weight: 7 },
            { name: "pan", count: 1, weight: 0 },
        ],
        tier_airdrop_armor: [
            { name: "helmet03", count: 1, weight: 1 },
            { name: "chest03", count: 1, weight: 1 },
            { name: "chest02", count: 1, weight: 2 },
            { name: "helmet02", count: 1, weight: 2 },
        ],
        tier_airdrop_scopes: [
            { name: "4xscope", count: 1, weight: 3 },
            // { name: "8xscope", count: 1, weight: 0 },
            // { name: "15xscope", count: 1, weight: 0 },
        ],

        tier_perks: [
            // { name: "", count: 1, weight: 20 },
            // { name: "splinter", count: 1, weight: 11.428 },
            //{ name: "scavenger", count: 1, weight: 11.428 },
            { name: "endless_ammo", count: 1, weight: 1 },
            //{ name: "takedown", count: 1, weight: 11.428 },
            { name: "field_medic", count: 1, weight: 1 },
            // { name: "bonus_assault", count: 1, weight: 11.428 },
            { name: "firepower", count: 1, weight: 1 },
            // { name: "lifesteal", count: 1, weight: 1 },
            // { name: "bulwark", count: 1, weight: 1 },
        ],
    },
    mapGen: {
        map: {
            baseWidth: 430,
            baseHeight: 430,
            scale: { small: 1.1875, large: 1.28125 },
            extension: 112,
            shoreInset: 48,
            grassInset: 18,
            rivers: {
                lakes: [],
                weights: [
                    { weight: 1, widths: [] },
                    // { weight: 0.1, widths: [4] },
                    // { weight: 0.15, widths: [8] },
                    // { weight: 0.25, widths: [8, 4] },
                    // { weight: 0.21, widths: [16] },
                    // { weight: 0.09, widths: [16, 8] },
                    // { weight: 0.2, widths: [16, 8, 4] },
                    // {
                    //     weight: 1e-4,
                    //     widths: [16, 16, 8, 6, 4],
                    // },
                ],
                smoothness: 0.45,
                spawnCabins: true,
                masks: [],
            },
        },
        places: [
            {
                name: "The Killpit",
                pos: v2.create(0.53, 0.64),
            },
            {
                name: "Sweatbath",
                pos: v2.create(0.84, 0.18),
            },
            {
                name: "Tarkhany",
                pos: v2.create(0.15, 0.11),
            },
            {
                name: "Ytyk-Kyuyol",
                pos: v2.create(0.25, 0.42),
            },
            {
                name: "Todesfelde",
                pos: v2.create(0.81, 0.85),
            },
            {
                name: "Pineapple",
                pos: v2.create(0.21, 0.79),
            },
            {
                name: "Fowl Forest",
                pos: v2.create(0.73, 0.47),
            },
            {
                name: "Ranchito Pollo",
                pos: v2.create(0.53, 0.25),
            },
        ],
        bridgeTypes: {
            medium: "bridge_md_structure_01",
            large: "bridge_lg_structure_01",
            xlarge: "",
        },
        customSpawnRules: {
            locationSpawns: [
                {
                    type: "club_complex_01",
                    pos: v2.create(0.5, 0.5),
                    rad: 150,
                    retryOnFailure: true,
                },
                {
                    type: "stone_04",
                    pos: v2.create(0.5, 0.5),
                    rad: 120,
                    retryOnFailure: true,
                },
            ],
            placeSpawns: ["warehouse_01", "house_red_01", "house_red_02", "barn_01"],
        },
        densitySpawns: [
            {
                stone_01: 300,
                barrel_01: 55,
                silo_01: 8,
                crate_01: 60,
                crate_02: 12,
                crate_03: 8,
                bush_01: 60 * 0.5,
                cache_06: 12,
                tree_01: 260,
                hedgehog_01: 24,
                container_01: 5,
                container_02: 5,
                container_03: 5,
                container_04: 5,
                shack_01: 7,
                outhouse_01: 5,
                loot_tier_1: 24,
                loot_tier_beach: 4,
            },
        ],
        fixedSpawns: [
            {
                // small is spawn count for solos and duos, large is spawn count for squads
                warehouse_01: 2,
                house_red_01: { small: 2, large: 4 },
                house_red_02: { small: 2, large: 3 },
                barn_01: { small: 2, large: 2 },
                barn_02: 1,
                hut_01: 1,
                hut_02: 1, // spas hut
                hut_03: 1, // scout hut
                shack_03a: 2,
                shack_03b: { small: 2, large: 3 },
                greenhouse_01: 1,
                cache_01: 1,
                cache_02: 0, // mosin tree
                cache_07: 1,
                bunker_structure_01: { odds: 0.05 },
                bunker_structure_02: 1,
                bunker_structure_03: 1,
                bunker_structure_04: 1,
                bunker_structure_05: 1,
                warehouse_complex_01: 1,
                chest_01: 1,
                chest_03: { odds: 0.2 },
                mil_crate_02: { odds: 0.25 },
                tree_02: 3,
                teahouse_complex_01su: {
                    small: 2,
                    large: 3,
                },
                stone_04: 1,
                club_complex_01: 1,
            },
        ],
        randomSpawns: [
            {
                spawns: ["mansion_structure_01", "police_01", "bank_01"],
                choose: 3,
            },
        ],
        spawnReplacements: [{}],
        importantSpawns: ["club_complex_01"],
    },
    /* STRIP_FROM_PROD_CLIENT:END */
};

type DeepPartial<T> = T extends object
    ? {
          [P in keyof T]?: DeepPartial<T[P]>;
      }
    : T;

export type PartialMapDef = DeepPartial<MapDef>;
