name: Deploy new replay client version to cloudflare pages

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      # for versioning
      - 'shared/gameConfig.ts'
      # for keeping the current version up to date
      - 'client/src/replay.ts'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Packages
        run: pnpm install

      - name: Write proxy config
        run: |
          cat > ./survev-config.hjson << 'EOF'
          {
            proxies: {
              default: {
                apiUrl: ${{ secrets.API_URL }}
              }
            }
          }
          EOF
      
      - name: Build client
        run: pnpm run build
        working-directory: ./client
      
      - name: Deploy
        run: pnpm tsx .github/workflows/scripts/deploy.ts
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}